title:  "IWSC 2018"
tagline: "12th International Workshop on Software Clones"
description:

# Authors documented under _data

# Change to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'millennial-3'

menu:
- {name: 'Registration', folder: 'pages', file: 'registration.html'}
- {name: 'Objectives', folder: 'pages', file: 'objectives.html'}
- {name: 'Program', folder: 'pages', file: 'program.html'}
- {name: 'Call for Papers', folder: 'pages', file: 'call_for_papers.html'}
- {name: 'Important Dates', folder: 'pages', file: 'important_dates.html'}
- {name: 'Keynote', folder: 'pages', file: 'keynote.html'}
- {name: 'Team', folder: 'pages', file: 'team.html'}

social:
- {icon: 'twitter', link: 'https://twitter.com/IWSC2017'}
- {icon: 'facebook', link: 'https://www.facebook.com/'}
# - {icon: 'instagram', link: 'https://instagram.com/paululele'}
# - {icon: 'envelope', link: 'mailto:l.nguyen.paul@gmail.com'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
